### ISSUE TITLE
Error installing on M1 MacBook Pro

### ISSUE THREAD

**Issue by clubdeuce** [krystal/deployhq-lib#12]
```
 gem install deployhq
Fetching deployhq-2.0.4.gem
Fetching websocket-native-1.0.0.gem
Fetching websocket-1.2.9.gem
Fetching eventmachine-1.2.7.gem
Fetching websocket-eventmachine-base-1.2.0.gem
Fetching websocket-eventmachine-client-1.3.0.gem
Fetching json-1.8.6.gem
Fetching highline-2.0.3.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
```

Running as `sudo` has the same error.

|package | version|
|---|---|
|ruby|2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]|
|gem|3.3.18|

<img width="584" alt="Screen Shot 2022-07-27 at 4 06 38 PM" src="https://user-images.githubusercontent.com/2600497/181362500-a03f6786-eb10-4543-aa6d-5933f00e55db.png">

**Comment by naft-a** [comment]
Please use a later version of ruby, i.e. `2.7.8` or later. The old versions have issues with M1 macs.
